language: go
go:
- tip
addons:
  postgresql: "9.4"
env:
  CHARON_POSTGRES_ADDRESS: postgres://postgres:@localhost/travis_ci_test?sslmode=disable
install:
- make get
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- make build
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: GlbUiPiSpa05wDHorgk+uOmupZ0kNNcaoGaJehhPRKrD6NZRgLr9bjrQgzHOKxZqgbK98l4aGPsCCJXtIw5bUrXu/Si7AaxzE4qP74FUnzpXkXxUxqexV+DAvI3WuPaqho7NXkqMs+EvYj/roM+ieuZ47jM2noPpPvLbw7Vp8CE=
