language: go
go:
- tip
addons:
  postgresql: '9.3'
env:
  CHARON_HOST: localhost
  CHARON_PORT: 9001
  CHARON_SUBSYSTEM: charon_travis
  CHARON_LOGGER_FORMAT: humane
  CHARON_LOGGER_ADAPTER: stdout
  CHARON_POSTGRES_CONNECTION_STRING: postgres://postgres:@localhost/travis_ci_test?sslmode=disable
before_install:
- pip install --user codecov
install:
- make get
script:
- make build
- make test-unit
- make test-postgres
after_success:
- codecov
notifications:
  slack:
    secure: GlbUiPiSpa05wDHorgk+uOmupZ0kNNcaoGaJehhPRKrD6NZRgLr9bjrQgzHOKxZqgbK98l4aGPsCCJXtIw5bUrXu/Si7AaxzE4qP74FUnzpXkXxUxqexV+DAvI3WuPaqho7NXkqMs+EvYj/roM+ieuZ47jM2noPpPvLbw7Vp8CE=
